# Generated by Django 2.1.7 on 2019-08-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='component',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
